name: Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Contribution Snake
        uses: githubcontribs/github-contribution-snake-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          snake_color: "#FABD2F"      # Gruvbox yellow
          border_color: "#504945"     # Gruvbox dark gray
          background_color: "#282828" # Gruvbox dark background
