name: Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Generate Snake
        run: npx github-contribution-snake --color "#FABD2F" --border "#504945" --bg "#282828" --output "./github-contribution-grid-snake.svg"
